name: CI/CD Pipeline

on: [push, pull_request]
  branches: [ main, develop, master ]

jobs:
  backend-tests:
    name: Backend Tests
    uses: ./.github/workflows/backend-tests.yml

  frontend-tests:
    name: Frontend Tests
    uses: ./.github/workflows/frontend-tests.yml

  build:
    name: Build and Test
    needs: [backend-tests, frontend-tests]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Display coverage reports
        run: |
          echo "Backend Coverage:"
          cat coverage/backend/coverage-final.json || echo "No backend coverage report found"
          echo "Frontend Coverage:"
          cat coverage/frontend/coverage-final.json || echo "No frontend coverage report found"

      - name: Build status
        run: |
          if [ ${{ needs.backend-tests.result }} == 'success' ] && [ ${{ needs.frontend-tests.result }} == 'success' ]; then
            echo "All tests passed successfully!"
            exit 0
          else
            echo "Some tests failed!"
            exit 1
          fi

  notify:
    name: Notify on failure
    needs: [build]
    if: failure()
    runs-on: ubuntu-latest
    
    steps:
      - name: Send notification
        run: |
          echo "Pipeline failed!"
          # Add notification logic here (e.g., Slack, email)

  deploy:
    name: Deploy
    needs: [build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Add deployment logic here 